import type { Config } from 'tailwindcss';
import plugin from 'tailwindcss/plugin';
import {
  RADIUS_SIZES,
  SHADES,
  SHADOW_SIZES,
  THEMED_COLOR_FAMILIES,
  buildThemeStyles,
  colorVar,
} from './src/theme/themeTokens';

// Every colour family the components use points at a CSS variable instead of a
// fixed hex, so switching `data-theme` on <html> re-colours the whole app.
// The variable values for each theme are generated by `buildThemeStyles()`.
const themedScale = (family: (typeof THEMED_COLOR_FAMILIES)[number]) =>
  Object.fromEntries(
    SHADES.map((shade) => [shade, `rgb(var(${colorVar(family, shade)}) / <alpha-value>)`]),
  );

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        ...Object.fromEntries(THEMED_COLOR_FAMILIES.map((family) => [family, themedScale(family)])),
        badminton: {
          green: `rgb(var(${colorVar('brand')}) / <alpha-value>)`,
          court: '#2d3748',
          line: '#ffffff',
        },
        backdrop: `rgb(var(${colorVar('backdrop')}) / <alpha-value>)`,
      },
      // Only *backgrounds* follow the theme's surface colour: `text-white` on a
      // coloured button must stay white even in the dark theme.
      backgroundColor: {
        white: `rgb(var(${colorVar('surface')}) / <alpha-value>)`,
      },
      fontFamily: {
        sans: 'var(--font-theme)',
      },
      borderRadius: Object.fromEntries(RADIUS_SIZES.map((size) => [size, `var(--radius-${size})`])),
      boxShadow: Object.fromEntries(SHADOW_SIZES.map((size) => [size, `var(--shadow-${size})`])),
    },
  },
  plugins: [plugin(({ addBase }) => addBase(buildThemeStyles()))],
} satisfies Config;
