import { DEFAULT_THEME_ID, THEME_IDS } from './themes';
import type { ThemeId } from './themes';

/**
 * Per-theme wording for the app's main user-facing text (screen titles,
 * buttons, lobby labels, dialog titles). `CLASSIC_COPY` is the original text;
 * other themes override whichever entries they want to re-word, section by
 * section, and fall back to the classic wording for the rest.
 *
 * The spoken match announcement is themed too (`announcement`): the words
 * around the player names, optionally naming the court.
 *
 * Deliberately left out: error / validation messages, import instructions,
 * table column headers and aria-labels - those need to stay plain and
 * unambiguous whatever the theme.
 */

/** Text with one bolded fragment in the middle: `[before, bold, after]`. */
export type Emphasized = readonly [string, string, string];
const em = (before: string, bold: string, after: string): Emphasized => [before, bold, after];

/** Text wrapped around a (bold) value: `[before, after]`. */
export type Wrapped = readonly [string, string];
const wrap = (before: string, after: string): Wrapped => [before, after];

/** A spoken closing phrase that names the court when it is known. */
const atCourt =
  (withCourt: (courtId: number) => string, fallback: string) =>
  (courtId?: number): string =>
    courtId ? withCourt(courtId) : fallback;

const CLASSIC_COPY = {
  app: {
    restoreTitle: '回復上次的比賽紀錄？',
    restoreDescription: '偵測到瀏覽器中有尚未完成的比賽資料，是否要繼續上次的進度？',
    restoreConfirm: '回復進度',
    restoreCancel: '不用，重新開始',
  },
  home: {
    tagline: '羽球排點系統。自動平衡實力、記錄戰績，讓每一次揮拍都充滿樂趣！',
    start: '打球啦',
  },
  steps: {
    back: '回上一步',
  },
  courts: {
    title: 'Step 1: 設定場地數量',
    subtitle: '請選擇今天的羽球場地數量',
    back: '回首頁',
    next: '下一步 (選擇模式)',
  },
  mode: {
    title: 'Step 2-1: 選擇對戰模式',
    subtitle: '選擇系統自動分組的邏輯',
    similarTitle: 'A. 相近模式',
    similarDescription: '選擇積分相近的選手對戰，打造勢均力敵的比賽。',
    balancedTitle: 'B. 平衡模式',
    balancedDescription: '高分帶低分，確保兩隊總積分接近。',
    mixedTitle: 'C. 混合模式',
    mixedDescription: '相近與平衡交替進行，依目前場次數自動平衡兩者比例。',
    next: '下一步 (選擇策略)',
  },
  strategy: {
    title: 'Step 2-2: 選擇系統策略',
    subtitle: '決定系統如何協助您進行分組',
    assistTitle: '輔助模式 (Assist)',
    assistSubtitle: '彈性優先，即時填補',
    assistDescription:
      '系統會持續監控佇列，當對戰組合不足時，自動「補上一場」建議對戰。適合喜歡頻繁手動分組，希望系統僅在空檔時提供協助的場景。缺點是若不常手動介入，分組多樣性較低（容易變成固定班底輪替）。',
    autoTitle: '自動模式 (Auto)',
    autoSubtitle: '多樣性優先，批次產生',
    autoDescription:
      '系統以「輪次 (Session)」為概念，一次產生涵蓋所有等待選手的對戰組合。此模式能最大化分組多樣性與公平性，適合全權交給系統安排。建議減少手動干預以維持最佳流暢度。',
    next: '下一步 (輸入名單)',
  },
  players: {
    title: 'Step 3: 選手名單',
    subtitle: '輸入參與比賽的選手資料 (最少 4 人)',
    add: '新增',
    total: '總人數',
    active: '上場',
    resting: '休息',
    generateTest: '產生測試選手',
    bulkImport: '批量匯入',
    empty: '尚無選手資料',
    statusActive: '準備上場',
    statusResting: '休息中',
    next: '下一步 (開始打球)',
    nextWhileEditing: '完成編輯 (回大廳)',
  },
  lobby: {
    title: '🏆 比賽大廳',
    assistBadge: '輔助模式',
    autoBadge: '自動模式',
    courts: '場地',
    playing: '進行中',
    waiting: '候位',
    total: '總人數',
    editRoster: '調整名單',
    manualMatch: '手動分組',
    finish: '結算',
    manualQueue: '預備分組 (優先上場)',
    suggested: '系統建議對戰',
    autoHint: '(自動模式: 預先排程)',
    notEnoughPlayers: '候位人數不足 4 人，無法產生建議。',
    computing: '計算最佳對戰組合中...',
    reshuffle: '換一組',
    allBusyTitle: '所有分組均有球員仍在場上',
    allBusyHint: '您可以等待場上比賽結束，或讓系統微調分組以立即開始。',
    autoAdjust: '系統自動微調',
  },
  court: {
    name: (courtId: number) => `場地 ${courtId}`,
    win: '勝',
    draw: '平手',
    requeue: '重排',
    noScore: '不計分',
    idle: '等待安排...',
  },
  match: {
    goToCourt: '上場',
    goNow: '立即上場',
    recommended: '推薦上場',
  },
  waiting: {
    title: '候位',
    empty: '全員皆在場上或已排程',
    neverPlayed: '尚未上場',
  },
  planned: {
    title: '預排上場順序',
    hint: '（場地一空出就依此順序上場）',
  },
  dialogs: {
    close: '關閉',
    finishTitle: '確定要結算戰績嗎？',
    finishBody: em('系統將', '停止產生新賽程', '，並進入最終戰績頁面。'),
    /** Wrapped around the (bold) number of unfinished matches. */
    finishUnfinished: wrap('目前場上/佇列尚有 ', ' 場未完成的比賽，這些場次不會計入最終戰績。'),
    finishConfirm: '確認結算',
    finishCancel: '繼續打球',
    noScoreTitle: '確認不計分下場？',
    noScoreBody: em('這將只會增加場上選手的', '「場次」', '，不會變動積分、勝敗或總得分。'),
    noScoreCourtCleared: '該場地將會清空。',
    noScoreConfirm: '確認下場',
    resultTitle: '比賽結束',
    resultSubtitle: '積分已更新',
    resultConfirm: '確認',
    historyTitle: '比賽歷史紀錄',
    statsTitle: '選手狀態統計',
  },
  stats: {
    title: '最終戰績結算',
    subtitle: 'Step 5: 比賽統計',
    copy: '簡易複製',
    history: '比賽歷程',
    done: '完成 (清空回到首頁)',
  },
  /** Spoken as "<intro> A, B <versus> C, D <outro(courtId)>". */
  announcement: {
    intro: '請',
    versus: '與',
    outro: atCourt(() => '上場', '上場'),
  },
};

export type Copy = typeof CLASSIC_COPY;
type CopyOverrides = { [Section in keyof Copy]?: Partial<Copy[Section]> };

/**
 * Dreamy storybook tone (童話 + 魔法 + 公主 + 積木): a kingdom built of toy bricks,
 * courts are brick castles, players are its princesses, wizards and heroes, and a fairy godmother arranges matches.
 */
const FAIRY_COPY: CopyOverrides = {
  app: {
    restoreTitle: '上次的童話還沒說完喔！',
    restoreDescription: '魔法書裡還夾著上次的書籤，要從那一頁繼續讀下去嗎？',
    restoreConfirm: '翻到書籤那一頁',
    restoreCancel: '打開新的故事書',
  },
  home: {
    tagline:
      '很久很久以前，在一座用積木堆成的魔法王國裡，公主、小巫師和勇者們最愛打羽球……仙女會幫大家配對、記錄戰績，每一場都是幸福快樂的結局！',
    start: '推開城堡大門 ✨',
  },
  steps: { back: '翻回上一頁' },
  courts: {
    title: '第一章：要堆幾座積木城堡？',
    subtitle: '今天的王國裡有幾座羽球場（積木城堡）呢？',
    back: '闔上故事書',
    next: '翻到下一頁（選一道魔法）',
  },
  mode: {
    title: '第二章：選一道配對魔法',
    subtitle: '決定仙女教母要怎麼幫大家分隊',
    similarTitle: 'A. 旗鼓相當咒',
    similarDescription: '讓實力相近的公主和勇者互相較量，每一場都是精彩的決鬥！',
    balancedTitle: 'B. 強弱互助咒',
    balancedDescription: '高強的騎士牽著剛入門的小巫師，兩隊的總魔力剛剛好。',
    mixedTitle: 'C. 積木百變咒',
    mixedDescription: '兩種魔法像積木一樣輪流疊上去，仙女會依場次自動調配比例。',
    next: '翻到下一頁（請魔法小幫手）',
  },
  strategy: {
    title: '第三章：請一位魔法小幫手',
    subtitle: '決定誰來幫王國安排比賽',
    assistTitle: '貼心小仙女 (Assist)',
    assistSubtitle: '隨時幫忙，即時補位',
    assistDescription:
      '小仙女會一直看著候場的居民，當對決組合不夠時，就「叮」地變出下一場建議。適合喜歡自己動手配對、只在空檔需要幫忙的王國。缺點是若很少親手安排，常常會是同一群好朋友輪流上場。',
    autoTitle: '仙女教母 (Auto)',
    autoSubtitle: '揮一揮魔杖，一次排好',
    autoDescription:
      '仙女教母以「一輪 (Session)」為單位，揮一下魔杖就替所有等待中的居民排好對決，讓大家都能和不同夥伴組隊、公平輪流。適合全權交給仙女教母，盡量少插手，故事會最順暢。',
    next: '翻到下一頁（寄出邀請函）',
  },
  players: {
    title: '第四章：王國居民名冊',
    subtitle: '寫下要來參加的公主、王子、小巫師與勇者（至少 4 位）',
    add: '寄出邀請函',
    total: '居民總數',
    active: '出場',
    resting: '休息',
    generateTest: '變出測試居民',
    bulkImport: '一次邀請一大群',
    empty: '名冊還是空白的，快寄出邀請函吧 💌',
    statusActive: '盛裝待命',
    statusResting: '在花園喝下午茶',
    next: '舞會開始（進入城堡）',
    nextWhileEditing: '寫好了（回到城堡）',
  },
  lobby: {
    title: '🏰 積木城堡大廳',
    assistBadge: '小仙女模式',
    autoBadge: '仙女教母模式',
    courts: '城堡球場',
    playing: '冒險中',
    waiting: '候場',
    total: '居民',
    editRoster: '修改名冊',
    manualMatch: '欽點組合',
    finish: '寫下結局',
    manualQueue: '欽點的組合 (優先出場)',
    suggested: '仙女推薦的對決',
    autoHint: '(仙女教母已預先排好)',
    notEnoughPlayers: '候場的居民不到 4 位，魔法變不出對決。',
    computing: '仙女正在一塊一塊堆出最棒的組合……🧱',
    reshuffle: '重新堆一組',
    allBusyTitle: '每一隊都有人還在城堡球場上',
    allBusyHint: '可以等他們下場，或請仙女施魔法調整隊伍，立刻開始新的對決。',
    autoAdjust: '請仙女施魔法調整',
  },
  court: {
    name: (courtId: number) => `積木城堡 ${courtId}`,
    win: '勝利！✨',
    draw: '和局',
    requeue: '拆掉重堆',
    noScore: '友誼賽',
    idle: '等待勇者到來……',
  },
  match: { goToCourt: '出場', goNow: '立刻出場', recommended: '仙女推薦' },
  waiting: {
    title: '候場的居民',
    empty: '所有居民都在球場上或已排好隊',
    neverPlayed: '還沒出場過',
  },
  planned: { title: '出場順序', hint: '（城堡球場一空出就依序出場）' },
  dialogs: {
    close: '闔上',
    finishTitle: '要寫下故事的結局了嗎？',
    finishBody: em('仙女將', '不再變出新的對決', '，並翻到最後一頁的戰績。'),
    finishUnfinished: wrap('現在還有 ', ' 場冒險沒完成，它們不會寫進最終戰績裡。'),
    finishConfirm: '寫下結局',
    finishCancel: '繼續冒險',
    noScoreTitle: '這場就當作友誼賽嗎？',
    noScoreBody: em('大家只會增加', '「出場次數」', '，積分、勝負和得分都不會改變。'),
    noScoreCourtCleared: '這座積木城堡會空出來。',
    noScoreConfirm: '友誼賽下場',
    resultTitle: '對決結束！✨',
    resultSubtitle: '大家的魔力值已經更新',
    resultConfirm: '好耶！',
    historyTitle: '冒險日誌',
    statsTitle: '居民狀態一覽',
  },
  stats: {
    title: '👑 故事的結局：最終戰績',
    subtitle: '尾聲：冒險紀錄',
    copy: '抄下居民名冊',
    history: '冒險歷程',
    done: '從此過著幸福快樂的日子（闔上故事書）',
  },
  announcement: {
    intro: '叮！仙女魔法召喚',
    versus: '與',
    outro: atCourt((courtId) => `請到積木城堡 ${courtId} 出場`, '請出場'),
  },
};

/** Insurance-salesperson tone: courts are coverage, players are the insured, finishing is settling the policy. */
const INSURANCE_COPY: CopyOverrides = {
  app: {
    restoreTitle: '您有一份尚未辦理完成的保單',
    restoreDescription: '系統偵測到您上次尚未完成的比賽資料，是否需要為您接續辦理？',
    restoreConfirm: '接續辦理',
    restoreCancel: '重新投保',
  },
  home: {
    tagline: '運動有保障，揮拍更安心。自動平衡實力、完整記錄戰績，羽中遨翔一路守護您的每一場比賽。',
    start: '立即投保・開始打球',
  },
  steps: {
    back: '返回上一步',
  },
  courts: {
    title: 'Step 1：評估您的保障額度（場地數量）',
    subtitle: '請選擇今日所需的羽球場地數量，我們將為您量身規劃',
    back: '返回首頁',
    next: '下一步：選擇方案',
  },
  mode: {
    title: 'Step 2-1：選擇對戰保障方案',
    subtitle: '請選擇最適合您團隊的分組方案',
    similarTitle: 'A. 實力相近型方案',
    similarDescription: '積分相近的選手互相對戰，風險分散、勢均力敵。',
    balancedTitle: 'B. 平衡保障型方案',
    balancedDescription: '高分帶低分，確保兩隊總積分接近，人人都有保障。',
    mixedTitle: 'C. 混合投資型方案',
    mixedDescription: '相近與平衡交替配置，依場次數自動調整比例，穩健又靈活。',
    next: '下一步：選擇服務',
  },
  strategy: {
    title: 'Step 2-2：選擇專屬服務',
    subtitle: '決定由哪一種服務模式協助您安排比賽',
    assistTitle: '專員陪同服務 (Assist)',
    assistSubtitle: '彈性服務，即時補位',
    assistDescription:
      '專員持續關注候位狀況，當對戰組合不足時，即時為您「補上一場」推薦對戰。適合偏好自行規劃、僅需專員在空檔時協助的客戶。提醒您：若較少手動安排，分組多樣性可能較低（容易變成固定班底輪替）。',
    autoTitle: '全權委託服務 (Auto)',
    autoSubtitle: '多元配置，一次到位',
    autoDescription:
      '以「期別 (Session)」為單位，一次為所有等待中的選手完成對戰配置，讓分組多樣性與公平性最大化。適合全權委託系統安排，建議減少手動干預，以維持最佳服務品質。',
    next: '下一步：建立被保險人名單',
  },
  players: {
    title: 'Step 3：被保險人名單',
    subtitle: '請填寫參加比賽的選手資料（至少 4 位）',
    add: '新增投保',
    total: '投保人數',
    active: '保障中',
    resting: '暫停',
    generateTest: '產生試算名單',
    bulkImport: '團體件匯入',
    empty: '目前尚無被保險人資料',
    statusActive: '保障生效中',
    statusResting: '暫停保障',
    next: '完成投保，開始打球',
    nextWhileEditing: '完成變更（返回服務大廳）',
  },
  lobby: {
    title: '🏢 客戶服務大廳',
    assistBadge: '專員陪同',
    autoBadge: '全權委託',
    courts: '承保場地',
    playing: '服務中',
    waiting: '候位',
    total: '被保險人',
    editRoster: '名單變更',
    manualMatch: '專案配置',
    finish: '期滿結算',
    manualQueue: '專案配置 (優先上場)',
    suggested: '本期推薦方案',
    autoHint: '(全權委託：預先排程)',
    notEnoughPlayers: '候位人數不足 4 位，暫時無法提供推薦方案。',
    computing: '正在為您試算最佳組合…',
    reshuffle: '換個方案',
    allBusyTitle: '所有方案均有被保險人仍在場上',
    allBusyHint: '您可以等待場上比賽結束，或由專員為您調整分組，立即開始。',
    autoAdjust: '專員協助調整',
  },
  court: {
    name: (courtId: number) => `第 ${courtId} 號場地`,
    requeue: '重新規劃',
    idle: '虛位以待，歡迎洽詢…',
  },
  match: {
    recommended: '專員推薦',
  },
  waiting: {
    title: '候位客戶',
    empty: '所有客戶皆已安排服務',
  },
  planned: {
    title: '預約上場順序',
    hint: '（場地一空出即依序為您安排）',
  },
  dialogs: {
    finishTitle: '確定要辦理期滿結算嗎？',
    finishBody: em('系統將', '停止承保新賽程', '，並為您產出最終戰績報告。'),
    finishUnfinished: wrap('目前尚有 ', ' 場未完成的比賽，將不列入理賠（最終戰績）計算。'),
    finishCancel: '繼續享有保障',
    noScoreTitle: '確認本場不計分？',
    noScoreBody: em('本場僅累計被保險人的', '「場次」', '，不影響積分、勝敗與總得分。'),
    noScoreCourtCleared: '該場地將釋出，開放下一組承保。',
    resultTitle: '比賽結束，理賠完成',
    resultSubtitle: '積分已依約定更新',
    historyTitle: '歷次服務紀錄',
    statsTitle: '被保險人狀態一覽',
  },
  stats: {
    title: '年度戰績結算報告',
    subtitle: 'Step 5：保障成果總覽',
    copy: '複製客戶名單',
    history: '服務紀錄',
    done: '結案 (清空回到首頁)',
  },
  announcement: {
    intro: '親愛的貴賓',
    versus: '與',
    outro: atCourt(
      (courtId) => `請至第 ${courtId} 號場地辦理上場，感謝您的配合`,
      '請辦理上場，感謝您的配合',
    ),
  },
};

/** Control-console tone: courts are compute nodes, players are users, matches are jobs. */
const TECH_COPY: CopyOverrides = {
  app: {
    restoreTitle: '偵測到未完成的工作階段',
    restoreDescription: '系統在本機快取中找到上次中斷的比賽資料，是否要從檢查點還原？',
    restoreConfirm: '還原工作階段',
    restoreCancel: '清除快取，重新開機',
  },
  home: {
    tagline:
      '> 羽球排點系統 v2.0 已上線。演算法自動平衡實力、即時記錄戰績，讓每一次揮拍都達到最佳效能。',
    start: '啟動系統',
  },
  steps: { back: '< 返回' },
  courts: {
    title: 'STEP 01 // 配置運算節點（場地數量）',
    subtitle: '請設定今日可用的球場節點數',
    back: '< 返回主畫面',
    next: '下一步 > 選擇演算法',
  },
  mode: {
    title: 'STEP 02 // 選擇配對演算法',
    subtitle: '設定系統自動分組所使用的邏輯',
    similarTitle: 'A. 相近匹配演算法',
    similarDescription: '比對積分相近的使用者進行對戰，將勝率誤差降到最低。',
    balancedTitle: 'B. 負載平衡演算法',
    balancedDescription: '高分節點搭配低分節點，讓兩隊總積分趨近一致。',
    mixedTitle: 'C. 混合排程演算法',
    mixedDescription: '相近與平衡交替執行，依目前場次數動態調整比例。',
    next: '下一步 > 選擇執行模式',
  },
  strategy: {
    title: 'STEP 03 // 選擇執行模式',
    subtitle: '決定系統如何協助你排程',
    assistTitle: '即時補位模式 (Assist)',
    assistSubtitle: '低延遲，隨需產生',
    assistDescription:
      '系統持續監控佇列，當對戰組合不足時即時補上一筆建議工作。適合經常手動調度、只需系統在閒置時補位的情境。缺點：若少有手動介入，分組多樣性較低（容易變成固定班底輪替）。',
    autoTitle: '批次排程模式 (Auto)',
    autoSubtitle: '高吞吐，批次產生',
    autoDescription:
      '系統以「批次 (Session)」為單位，一次為所有等待中的使用者產生對戰組合，將分組多樣性與公平性最佳化。適合全自動執行，建議減少手動干預以維持最佳效能。',
    next: '下一步 > 載入使用者',
  },
  players: {
    title: 'STEP 04 // 使用者清單',
    subtitle: '輸入參與比賽的使用者資料（最少 4 筆）',
    add: '+ 新增',
    total: '使用者總數',
    active: '上線',
    resting: '離線',
    generateTest: '產生測試資料',
    bulkImport: '批次匯入',
    empty: 'NULL — 尚無使用者資料',
    statusActive: '● 上線待命',
    statusResting: '○ 離線休眠',
    next: '部署並開始比賽',
    nextWhileEditing: '套用變更（返回控制中心）',
  },
  lobby: {
    title: '🖥️ 比賽控制中心',
    assistBadge: '即時補位',
    autoBadge: '批次排程',
    courts: '節點',
    playing: '執行中',
    waiting: '佇列',
    total: '使用者',
    editRoster: '編輯清單',
    manualMatch: '手動建立工作',
    finish: '關機結算',
    manualQueue: '手動工作 (高優先權)',
    suggested: '演算法推薦對戰',
    autoHint: '(批次排程：已預先運算)',
    notEnoughPlayers: 'ERROR: 佇列中使用者不足 4 位，無法產生建議。',
    computing: '運算最佳組合中… ▮▮▮▯▯',
    reshuffle: '重新運算',
    allBusyTitle: '所有工作皆有使用者仍在執行中',
    allBusyHint: '可等待執行中的比賽結束，或讓系統自動調整分組以立即執行。',
    autoAdjust: '自動最佳化',
  },
  court: {
    name: (courtId: number) => `NODE-${String(courtId).padStart(2, '0')}`,
    win: 'WIN',
    draw: 'DRAW',
    requeue: '退回佇列',
    noScore: '不計分',
    idle: '閒置中… 等待工作',
  },
  match: { goToCourt: '執行', goNow: '立即執行', recommended: '系統推薦' },
  waiting: { title: '等待佇列', empty: '所有使用者皆已執行或排程', neverPlayed: '尚未執行' },
  planned: { title: '預排執行順序', hint: '（節點一閒置就依序執行）' },
  dialogs: {
    finishTitle: '確定要關機並結算嗎？',
    finishBody: em('系統將', '停止產生新的排程', '，並輸出最終戰績報表。'),
    finishUnfinished: wrap('目前仍有 ', ' 筆未完成的工作，不會寫入最終戰績。'),
    finishConfirm: '確認關機',
    finishCancel: '繼續執行',
    noScoreTitle: '確認以不計分結束此工作？',
    noScoreBody: em('只會累加使用者的', '「場次」', '，不會寫入積分、勝敗或總得分。'),
    noScoreCourtCleared: '該節點將釋放資源。',
    noScoreConfirm: '確認結束',
    resultTitle: '工作完成 ✔',
    resultSubtitle: '積分資料已同步更新',
    resultConfirm: 'OK',
    historyTitle: '執行日誌',
    statsTitle: '使用者狀態監控',
  },
  stats: {
    title: '最終戰績報表',
    subtitle: 'STEP 05 // 統計輸出',
    copy: '匯出資料',
    history: '執行歷程',
    done: '關機（清空並回到主畫面）',
  },
  announcement: {
    intro: '系統通知，使用者',
    versus: '對戰',
    outro: atCourt((courtId) => `請連線至第 ${courtId} 號節點，開始執行`, '開始執行'),
  },
};

/** Courtroom tone: a court is a courtroom, the two pairs are plaintiff and defendant, winning is 勝訴. */
const LAWSUIT_COPY: CopyOverrides = {
  app: {
    restoreTitle: '本案尚未審結，是否續行審理？',
    restoreDescription: '本院查有上次尚未審結之比賽卷宗，是否依原卷宗續行審理？',
    restoreConfirm: '續行審理',
    restoreCancel: '撤回，另行起訴',
  },
  home: {
    tagline: '本院依公平原則，自動平衡雙方實力、詳實記錄每一次判決，讓每一場比賽都經得起上訴。',
    start: '開庭！',
  },
  steps: { back: '退回前一程序' },
  courts: {
    title: '第一審：開設幾間法庭？',
    subtitle: '請裁定今日可使用之羽球場（法庭）數量',
    back: '退庭回首頁',
    next: '下一程序（選擇審理原則）',
  },
  mode: {
    title: '第二審：選擇審理原則',
    subtitle: '裁定系統分組所依據之法理',
    similarTitle: 'A. 實力相當原則',
    similarDescription: '積分相近之當事人相互對決，攻防勢均力敵。',
    balancedTitle: 'B. 衡平原則',
    balancedDescription: '高分者與低分者搭配，使雙方總積分趨於衡平。',
    mixedTitle: 'C. 折衷原則',
    mixedDescription: '相近與衡平兩原則交替適用，依場次數自動調整比例。',
    next: '下一程序（選任協助人員）',
  },
  strategy: {
    title: '第三審：選任協助人員',
    subtitle: '決定由何人協助本院安排比賽',
    assistTitle: '書記官協助制 (Assist)',
    assistSubtitle: '彈性審理，隨時補位',
    assistDescription:
      '書記官持續關注候審名單，對戰組合不足時即時「補上一場」建議。適合法官偏好親自分案、僅於空檔需協助之情形。惟若甚少親自分案，分組多樣性較低（易成固定班底輪替）。',
    autoTitle: '自動分案制 (Auto)',
    autoSubtitle: '公平輪分，批次分案',
    autoDescription:
      '以「庭期 (Session)」為單位，一次將所有候審當事人分案完畢，最大化分組多樣性與公平性。適合全權委由系統分案，建議減少人工干預以維持審理順暢。',
    next: '下一程序（傳喚當事人）',
  },
  players: {
    title: '傳喚當事人',
    subtitle: '請登載到庭當事人資料（至少 4 人）',
    add: '傳喚到庭',
    total: '當事人總數',
    active: '到庭',
    resting: '請假',
    generateTest: '傳喚測試當事人',
    bulkImport: '整批傳喚',
    empty: '本案尚無當事人到庭',
    statusActive: '到庭候審',
    statusResting: '請假未到',
    next: '正式開庭（進入法院）',
    nextWhileEditing: '更正完畢（返回法院大廳）',
  },
  lobby: {
    title: '⚖️ 地方法院大廳',
    assistBadge: '書記官協助',
    autoBadge: '自動分案',
    courts: '法庭',
    playing: '審理中',
    waiting: '候審',
    total: '當事人',
    editRoster: '更正名冊',
    manualMatch: '指定分案',
    finish: '宣判',
    manualQueue: '指定分案 (優先審理)',
    suggested: '本院建議庭期',
    autoHint: '(自動分案：已排定庭期)',
    notEnoughPlayers: '候審當事人不足 4 人，無法排定庭期。',
    computing: '合議庭評議中……',
    reshuffle: '改分他案',
    allBusyTitle: '所有案件均有當事人仍在庭上',
    allBusyHint: '可待庭上案件審結，或由系統調整分案以立即開庭。',
    autoAdjust: '依職權調整',
  },
  court: {
    name: (courtId: number) => `第 ${courtId} 法庭`,
    win: '勝訴',
    draw: '和解',
    requeue: '發回更審',
    noScore: '不起訴',
    idle: '休庭中……',
  },
  match: { goToCourt: '開庭', goNow: '立即開庭', recommended: '本院建議' },
  waiting: { title: '候審當事人', empty: '全體當事人均已到庭或排定庭期', neverPlayed: '尚未出庭' },
  planned: { title: '預定開庭順序', hint: '（法庭一空出即依序開庭）' },
  dialogs: {
    close: '退庭',
    finishTitle: '確定要宣判嗎？',
    finishBody: em('本院將', '停止受理新案件', '，並宣讀最終判決（戰績）。'),
    finishUnfinished: wrap('目前尚有 ', ' 件未審結之案件，不列入最終判決。'),
    finishConfirm: '宣判',
    finishCancel: '繼續審理',
    noScoreTitle: '確定為不起訴處分？',
    noScoreBody: em('本件僅記錄當事人之', '「出庭次數」', '，不影響積分、勝敗或總得分。'),
    noScoreCourtCleared: '該法庭將予清空。',
    noScoreConfirm: '不起訴處分',
    resultTitle: '判決確定',
    resultSubtitle: '雙方積分已依判決更新',
    resultConfirm: '服判',
    historyTitle: '歷審判決紀錄',
    statsTitle: '當事人狀態一覽',
  },
  stats: {
    title: '最終判決書：戰績結算',
    subtitle: '判決理由：比賽統計',
    copy: '抄錄當事人名冊',
    history: '審理經過',
    done: '全案終結（清空回到首頁）',
  },
  announcement: {
    intro: '傳喚當事人',
    versus: '對',
    outro: atCourt((courtId) => `請至第 ${courtId} 法庭，準備開庭`, '請準備開庭'),
  },
};

/** Greek-myth tone: courts are arenas, players are heroes, the system is an oracle. */
const GREEK_COPY: CopyOverrides = {
  app: {
    restoreTitle: '眾神記得上一場未竟的競技',
    restoreDescription: '神諭顯示上次的比賽尚未結束，英雄們要回到競技場繼續嗎？',
    restoreConfirm: '重返競技場',
    restoreCancel: '開啟新的史詩',
  },
  home: {
    tagline:
      '在奧林帕斯眾神的注視下，神諭自動平衡英雄實力、刻下每一場戰績，讓每一次揮拍都成為傳說。',
    start: '登上奧林帕斯！',
  },
  steps: { back: '回到上一篇章' },
  courts: {
    title: '第一篇章：開放幾座競技場？',
    subtitle: '今日眾神為英雄們準備了幾座羽球競技場？',
    back: '回到神殿入口',
    next: '下一篇章（求取神諭）',
  },
  mode: {
    title: '第二篇章：求取對決的神諭',
    subtitle: '決定神諭如何為英雄分隊',
    similarTitle: 'A. 勢均力敵的試煉',
    similarDescription: '讓實力相近的英雄彼此較量，每一場都是諸神也屏息的對決。',
    balancedTitle: 'B. 正義女神的天平',
    balancedDescription: '強大的半神帶領凡人英雄，讓兩隊總力量在天平上持平。',
    mixedTitle: 'C. 命運女神的紡線',
    mixedDescription: '兩種神諭交織輪替，命運女神會依場次自動調配比例。',
    next: '下一篇章（選擇守護神）',
  },
  strategy: {
    title: '第三篇章：選擇守護神',
    subtitle: '決定哪位神祇協助你安排競技',
    assistTitle: '信使荷米斯 (Assist)',
    assistSubtitle: '神速傳訊，即時補位',
    assistDescription:
      '荷米斯時時留意等候的英雄，對決組合不足時，立刻捎來「下一場」的神諭。適合喜歡親自分配、只在空檔需要神助的城邦。缺點是若很少親自安排，常常會是同一群英雄輪流上場。',
    autoTitle: '德爾菲神諭 (Auto)',
    autoSubtitle: '預見全局，一次排定',
    autoDescription:
      '神諭以「一輪 (Session)」為單位，一次為所有等候的英雄預言好對決，讓分組最多樣、輪替最公平。適合全權交給神諭，盡量少干預，史詩會最流暢。',
    next: '下一篇章（召集英雄）',
  },
  players: {
    title: '第四篇章：英雄名冊',
    subtitle: '寫下參加競技的英雄（至少 4 位）',
    add: '召喚英雄',
    total: '英雄總數',
    active: '出征',
    resting: '休憩',
    generateTest: '召喚測試英雄',
    bulkImport: '集結軍團',
    empty: '名冊空無一人，快召喚英雄吧！',
    statusActive: '整裝待戰',
    statusResting: '在橄欖樹下休憩',
    next: '開始競技（進入競技場）',
    nextWhileEditing: '名冊完成（返回競技場）',
  },
  lobby: {
    title: '🏛️ 奧林帕斯競技場',
    assistBadge: '荷米斯協助',
    autoBadge: '德爾菲神諭',
    courts: '競技場',
    playing: '激戰中',
    waiting: '候戰',
    total: '英雄',
    editRoster: '修訂名冊',
    manualMatch: '親點對決',
    finish: '眾神裁決',
    manualQueue: '親點的對決 (優先出戰)',
    suggested: '神諭預示的對決',
    autoHint: '(德爾菲神諭：已預言)',
    notEnoughPlayers: '候戰英雄不足 4 位，神諭無法顯現。',
    computing: '女祭司正在解讀神諭……',
    reshuffle: '重求神諭',
    allBusyTitle: '每一組都有英雄仍在競技場上',
    allBusyHint: '可等待場上激戰結束，或請神諭調整分組，立刻展開新對決。',
    autoAdjust: '請求神諭調整',
  },
  court: {
    name: (courtId: number) => `第 ${courtId} 競技場`,
    win: '凱旋',
    draw: '平分秋色',
    requeue: '重新分組',
    noScore: '友誼切磋',
    idle: '等待英雄降臨……',
  },
  match: { goToCourt: '出戰', goNow: '立即出戰', recommended: '神諭推薦' },
  waiting: { title: '候戰英雄', empty: '所有英雄都已出戰或排定', neverPlayed: '尚未出戰' },
  planned: { title: '出戰順序', hint: '（競技場一空出就依序出戰）' },
  dialogs: {
    finishTitle: '要請眾神做出最終裁決嗎？',
    finishBody: em('神諭將', '不再預示新的對決', '，並將戰績刻上神殿石碑。'),
    finishUnfinished: wrap('此刻仍有 ', ' 場對決未分勝負，不會刻入最終戰績。'),
    finishConfirm: '請眾神裁決',
    finishCancel: '繼續競技',
    noScoreTitle: '這場只是友誼切磋嗎？',
    noScoreBody: em('英雄們只會增加', '「出戰次數」', '，積分、勝負與得分都不改變。'),
    noScoreCourtCleared: '這座競技場將清空。',
    noScoreConfirm: '切磋結束',
    resultTitle: '勝負已定！',
    resultSubtitle: '眾神已更新英雄的榮耀',
    resultConfirm: '榮耀歸於眾神',
    historyTitle: '英雄史詩',
    statsTitle: '英雄狀態一覽',
  },
  stats: {
    title: '神殿石碑：最終戰績',
    subtitle: '終章：競技紀錄',
    copy: '抄錄英雄名冊',
    history: '史詩篇章',
    done: '史詩落幕（回到神殿入口）',
  },
  announcement: {
    intro: '眾神召喚英雄',
    versus: '與',
    outro: atCourt((courtId) => `前往第 ${courtId} 競技場，迎接試煉`, '出戰，迎接試煉'),
  },
};

/** Can't-be-bothered tone: everything is a chore, the lobby is a sofa. */
const SLACKER_COPY: CopyOverrides = {
  app: {
    restoreTitle: '上次好像沒打完耶…',
    restoreDescription:
      '瀏覽器裡還留著上次打到一半的資料，要接著打嗎？還是乾脆重來（雖然也很麻煩）？',
    restoreConfirm: '接著打吧',
    restoreCancel: '算了重來',
  },
  home: {
    tagline: '羽球排點系統。反正它會自己平衡實力、自己記戰績，你只要……嗯，揮揮拍就好了吧。',
    start: '喔好啦…打就打',
  },
  steps: { back: '算了，回去' },
  courts: {
    title: 'Step 1：要幾面場…隨便啦',
    subtitle: '選一下今天有幾面場，選錯也沒差',
    back: '不想打了回首頁',
    next: '下一步（好麻煩）',
  },
  mode: {
    title: 'Step 2-1：選個模式…看哪個順眼',
    subtitle: '系統會自己分組，你挑一個就好',
    similarTitle: 'A. 差不多的一起打',
    similarDescription: '程度差不多的湊一場，大家都不用太認真。',
    balancedTitle: 'B. 強的帶弱的',
    balancedDescription: '強的帶弱的，這樣兩邊加起來差不多，很公平（大概）。',
    mixedTitle: 'C. 兩個混著來',
    mixedDescription: '懶得選的話就這個，系統會自己輪流。',
    next: '下一步（還有喔…）',
  },
  strategy: {
    title: 'Step 2-2：要自己排還是給系統排',
    subtitle: '推薦給系統排，比較不累',
    assistTitle: '偶爾幫一下 (Assist)',
    assistSubtitle: '沒人了才補一場',
    assistDescription:
      '系統會盯著排隊的人，組合不夠才補一場給你。適合喜歡自己動手分組的勤勞人士（不是我）。缺點是如果你也懶得手動，常常會是同一群人輪來輪去。',
    autoTitle: '全部丟給它 (Auto)',
    autoSubtitle: '一次排好，完全不用管',
    autoDescription:
      '系統以「一輪 (Session)」為單位，一次把所有等待的人排好，分組又多樣又公平。最適合什麼都不想管的你，盡量別手動插手就好。',
    next: '下一步（快好了吧）',
  },
  players: {
    title: 'Step 3：誰要打…報一下名',
    subtitle: '輸入一下要打的人（至少 4 個，不然打不起來）',
    add: '加啦',
    total: '人數',
    active: '有要打',
    resting: '在耍廢',
    generateTest: '隨便生幾個人',
    bulkImport: '一次貼一堆',
    empty: '一個人都沒有…那就先躺著吧',
    statusActive: '勉強上場',
    statusResting: '躺平中',
    next: '好啦開打（開始打球）',
    nextWhileEditing: '改完了（回沙發）',
  },
  lobby: {
    title: '🛋️ 躺平大廳',
    assistBadge: '偶爾幫一下',
    autoBadge: '全部丟給它',
    courts: '場地',
    playing: '在打',
    waiting: '排隊',
    total: '人數',
    editRoster: '改一下名單',
    manualMatch: '自己湊一組',
    finish: '收工',
    manualQueue: '自己湊的 (先上)',
    suggested: '系統隨便排的',
    autoHint: '(已經先排好了，不用管)',
    notEnoughPlayers: '排隊的人不到 4 個，湊不出來啦。',
    computing: '腦袋轉很慢，等一下……',
    reshuffle: '換一組啦',
    allBusyTitle: '每組都有人還在場上打',
    allBusyHint: '等他們打完，或讓系統自己調一下就能開打了。',
    autoAdjust: '叫系統自己調',
  },
  court: {
    name: (courtId: number) => `${courtId} 號場`,
    win: '贏了（爽）',
    draw: '都差不多',
    requeue: '退回去',
    noScore: '不算了啦',
    idle: '沒人……先躺一下',
  },
  match: { goToCourt: '上吧', goNow: '快上啦', recommended: '就這組吧' },
  waiting: { title: '在排隊的', empty: '大家都在打或排好了，可以休息了', neverPlayed: '還沒打過' },
  planned: { title: '等一下的順序', hint: '（有空場就照這個上，不用想）' },
  dialogs: {
    close: '關掉',
    finishTitle: '要收工了嗎？',
    finishBody: em('系統會', '不再排新的比賽', '，然後直接看最後戰績。'),
    finishUnfinished: wrap('還有 ', ' 場沒打完，那些就不算了喔。'),
    finishConfirm: '收工收工',
    finishCancel: '再打一下',
    noScoreTitle: '這場不算了？',
    noScoreBody: em('只會幫大家加', '「場次」', '，積分、勝負、得分都不動。'),
    noScoreCourtCleared: '場地會空出來。',
    noScoreConfirm: '不算了',
    resultTitle: '打完了，終於',
    resultSubtitle: '積分自己更新好了',
    resultConfirm: '嗯',
    historyTitle: '打過的（懶得看的話可以跳過）',
    statsTitle: '大家的狀況',
  },
  stats: {
    title: '總結一下戰績',
    subtitle: 'Step 5：看看就好',
    copy: '複製一下',
    history: '打過的比賽',
    done: '收工回家（清空回首頁）',
  },
  announcement: {
    intro: '欸……',
    versus: '跟',
    outro: atCourt((courtId) => `輪到你們了啦，去 ${courtId} 號場打一下`, '輪到你們了啦'),
  },
};

/** Diner tone: courts are tables, players are diners, a match is a dish being served. */
const FOODIE_COPY: CopyOverrides = {
  app: {
    restoreTitle: '上一餐還沒吃完喔！',
    restoreDescription: '桌上還留著上次沒吃完的比賽，要幫你熱一熱繼續吃嗎？',
    restoreConfirm: '熱一熱繼續吃',
    restoreCancel: '收掉，重新點餐',
  },
  home: {
    tagline:
      '羽球排點系統。主廚幫你把實力搭配得剛剛好、把戰績記進菜單，每一次揮拍都像咬下一口熱騰騰的美食！',
    start: '開飯囉！🍚',
  },
  steps: { back: '回上一道' },
  courts: {
    title: '第一道：今天開幾桌？',
    subtitle: '選一下今天有幾面球場（餐桌）',
    back: '回到門口',
    next: '下一道（選擇料理方式）',
  },
  mode: {
    title: '第二道：選擇料理方式',
    subtitle: '決定主廚怎麼幫大家配菜',
    similarTitle: 'A. 同口味拼盤',
    similarDescription: '口味（積分）相近的一起上桌，吃起來旗鼓相當。',
    balancedTitle: 'B. 酸甜均衡套餐',
    balancedDescription: '重口味搭清淡，讓兩隊總份量剛剛好。',
    mixedTitle: 'C. 主廚綜合拼盤',
    mixedDescription: '兩種做法輪流上菜，主廚依場次自動調整比例。',
    next: '下一道（選擇服務方式）',
  },
  strategy: {
    title: '第三道：選擇服務方式',
    subtitle: '決定要怎麼幫你上菜',
    assistTitle: '單點現做 (Assist)',
    assistSubtitle: '要吃再做，隨點隨上',
    assistDescription:
      '服務生一直看著候位的客人，菜不夠時就立刻「加點一道」推薦對戰。適合喜歡自己點菜、只在空檔需要推薦的饕客。缺點是若很少自己點，常常會是同一桌熟客輪流吃。',
    autoTitle: '主廚套餐 (Auto)',
    autoSubtitle: '一次出好，道道豐盛',
    autoDescription:
      '主廚以「一輪 (Session)」為單位，一次為所有候位客人配好菜，讓搭配最多樣、輪替最公平。適合全權交給主廚，盡量不要改菜單，上菜最順暢。',
    next: '下一道（登記食客）',
  },
  players: {
    title: '第四道：今日食客名單',
    subtitle: '登記一下今天來吃（打）的人（至少 4 位）',
    add: '加一位',
    total: '食客總數',
    active: '開動',
    resting: '吃飽了',
    generateTest: '來幾位試吃員',
    bulkImport: '團體訂位',
    empty: '還沒有客人上門，快去拉客！',
    statusActive: '餓了想打',
    statusResting: '吃飽休息中',
    next: '開動！（開始打球）',
    nextWhileEditing: '點好了（回到餐廳）',
  },
  lobby: {
    title: '🍽️ 美食街大廳',
    assistBadge: '單點現做',
    autoBadge: '主廚套餐',
    courts: '餐桌',
    playing: '用餐中',
    waiting: '候位',
    total: '食客',
    editRoster: '修改訂位',
    manualMatch: '自己配菜',
    finish: '買單',
    manualQueue: '自己配的菜 (優先上桌)',
    suggested: '今日主廚推薦',
    autoHint: '(主廚套餐：已備好料)',
    notEnoughPlayers: '候位客人不到 4 位，還湊不成一桌。',
    computing: '主廚正在備料中……🔥',
    reshuffle: '換一道菜',
    allBusyTitle: '每一桌都還有客人在用餐',
    allBusyHint: '可以等他們吃完，或請主廚調整菜色，馬上開桌。',
    autoAdjust: '請主廚調整',
  },
  court: {
    name: (courtId: number) => `第 ${courtId} 桌`,
    win: '勝！加菜',
    draw: '平手乾杯',
    requeue: '退回廚房',
    noScore: '試吃不算',
    idle: '空桌，等客人入座……',
  },
  match: { goToCourt: '上菜', goNow: '馬上上菜', recommended: '主廚推薦' },
  waiting: { title: '候位的客人', empty: '所有客人都已入座或點好餐', neverPlayed: '還沒吃到' },
  planned: { title: '上菜順序', hint: '（餐桌一空出就依序上菜）' },
  dialogs: {
    finishTitle: '要買單結帳了嗎？',
    finishBody: em('廚房將', '停止出菜', '，並送上最終戰績帳單。'),
    finishUnfinished: wrap('目前還有 ', ' 道菜沒吃完，不會算進最終帳單。'),
    finishConfirm: '買單',
    finishCancel: '再吃一點',
    noScoreTitle: '這場算試吃嗎？',
    noScoreBody: em('只會記一次', '「用餐次數」', '，積分、勝負和得分都不改變。'),
    noScoreCourtCleared: '這桌會收拾乾淨。',
    noScoreConfirm: '試吃結束',
    resultTitle: '這道吃完了！😋',
    resultSubtitle: '積分已記到帳上',
    resultConfirm: '好吃！',
    historyTitle: '用餐紀錄',
    statsTitle: '食客狀態一覽',
  },
  stats: {
    title: '🧾 最終帳單：戰績結算',
    subtitle: '飯後甜點：比賽統計',
    copy: '抄下食客名單',
    history: '今日菜單',
    done: '吃飽回家（清空回到首頁）',
  },
  announcement: {
    intro: '叮咚！餐點好了，請',
    versus: '與',
    outro: atCourt((courtId) => `到第 ${courtId} 桌開動囉`, '上桌開動囉'),
  },
};

/** Air-travel tone: courts are gates, players are passengers, going on court is boarding. */
const TRAVEL_COPY: CopyOverrides = {
  app: {
    restoreTitle: '您有一段未完成的旅程',
    restoreDescription: '系統找到上次尚未完成的比賽行程，要繼續這段旅程嗎？',
    restoreConfirm: '繼續旅程',
    restoreCancel: '重新規劃行程',
  },
  home: {
    tagline: '羽球排點系統。自動安排旅伴、記錄每一站的戰績，讓每一次揮拍都是一趟難忘的旅程！',
    start: '出發旅行 ✈️',
  },
  steps: { back: '回上一站' },
  courts: {
    title: 'Step 1：開放幾個登機門？',
    subtitle: '請選擇今日可用的羽球場（登機門）數量',
    back: '回到出境大廳',
    next: '下一站（選擇行程風格）',
  },
  mode: {
    title: 'Step 2-1：選擇行程風格',
    subtitle: '決定系統怎麼幫大家安排旅伴',
    similarTitle: 'A. 同好旅行團',
    similarDescription: '實力相近的旅客同團出發，一路勢均力敵。',
    balancedTitle: 'B. 老手帶新手',
    balancedDescription: '資深背包客帶新手，兩隊總積分剛剛好。',
    mixedTitle: 'C. 自由混搭行',
    mixedDescription: '兩種行程交替安排，依場次數自動調整比例。',
    next: '下一站（選擇導遊）',
  },
  strategy: {
    title: 'Step 2-2：選擇導遊服務',
    subtitle: '決定由誰幫你安排行程',
    assistTitle: '隨行導遊 (Assist)',
    assistSubtitle: '隨走隨排，彈性自由行',
    assistDescription:
      '導遊隨時留意候機的旅客，組合不夠時就立刻「加開一班」推薦對戰。適合喜歡自己規劃、只在空檔需要建議的自由行旅客。缺點是若很少自己安排，常常會是同一群旅伴輪流出發。',
    autoTitle: '全包團行程 (Auto)',
    autoSubtitle: '一次排好，輕鬆跟團',
    autoDescription:
      '以「一個梯次 (Session)」為單位，一次為所有候機旅客排好班次，讓旅伴搭配最多樣、輪替最公平。適合全權交給旅行社，盡量少改行程，旅途最順暢。',
    next: '下一站（登記旅客）',
  },
  players: {
    title: 'Step 3：旅客名單',
    subtitle: '登記這趟旅程的旅客（至少 4 位）',
    add: '加入旅客',
    total: '旅客總數',
    active: '出發',
    resting: '留宿',
    generateTest: '產生測試旅客',
    bulkImport: '團體報名',
    empty: '還沒有旅客報名，快揪團吧！',
    statusActive: '準備登機',
    statusResting: '在飯店休息',
    next: '出發！（開始打球）',
    nextWhileEditing: '名單確認（回到航廈）',
  },
  lobby: {
    title: '✈️ 國際航廈大廳',
    assistBadge: '隨行導遊',
    autoBadge: '全包團',
    courts: '登機門',
    playing: '飛行中',
    waiting: '候機',
    total: '旅客',
    editRoster: '修改旅客名單',
    manualMatch: '自組旅伴',
    finish: '旅程結束',
    manualQueue: '自組旅伴 (優先登機)',
    suggested: '推薦航班',
    autoHint: '(全包團：航班已排定)',
    notEnoughPlayers: '候機旅客不足 4 位，還湊不成一班。',
    computing: '正在安排最佳航線……🧭',
    reshuffle: '換個航班',
    allBusyTitle: '每一班都有旅客仍在飛行中',
    allBusyHint: '可以等飛機降落，或讓系統調整旅伴，立即起飛。',
    autoAdjust: '調整航班',
  },
  court: {
    name: (courtId: number) => `登機門 ${courtId}`,
    win: '勝 ✈️',
    draw: '平手',
    requeue: '改搭下一班',
    noScore: '航班取消',
    idle: '等待旅客登機……',
  },
  match: { goToCourt: '登機', goNow: '立即登機', recommended: '推薦航班' },
  waiting: { title: '候機旅客', empty: '所有旅客都已登機或排定航班', neverPlayed: '尚未出發' },
  planned: { title: '預定起飛順序', hint: '（登機門一空出就依序起飛）' },
  dialogs: {
    finishTitle: '旅程要在這裡結束了嗎？',
    finishBody: em('系統將', '不再安排新的航班', '，並為你製作旅行紀念冊（最終戰績）。'),
    finishUnfinished: wrap('目前還有 ', ' 個航班尚未抵達，不會收進紀念冊裡。'),
    finishConfirm: '結束旅程',
    finishCancel: '再玩一站',
    noScoreTitle: '確定取消這個航班？',
    noScoreBody: em('旅客只會累積', '「出發次數」', '，積分、勝負和得分都不改變。'),
    noScoreCourtCleared: '這個登機門將開放給下一班。',
    noScoreConfirm: '取消航班',
    resultTitle: '平安抵達！',
    resultSubtitle: '里程（積分）已更新',
    resultConfirm: '收下紀念章',
    historyTitle: '旅行日記',
    statsTitle: '旅客狀態一覽',
  },
  stats: {
    title: '📸 旅行紀念冊：最終戰績',
    subtitle: 'Step 5：旅程回顧',
    copy: '複製旅客名單',
    history: '一路走過的航程',
    done: '平安回家（清空回到首頁）',
  },
  announcement: {
    intro: '各位旅客請注意，請',
    versus: '與',
    outro: atCourt((courtId) => `前往登機門 ${courtId} 登機`, '前往登機'),
  },
};

/** Detective tone: courts are crime scenes, players are suspects, the system deduces. */
const DETECTIVE_COPY: CopyOverrides = {
  app: {
    restoreTitle: '發現一件未破的懸案！',
    restoreDescription: '偵探事務所的檔案櫃裡還有上次沒辦完的比賽卷宗，要繼續調查嗎？',
    restoreConfirm: '繼續調查',
    restoreCancel: '封存卷宗，接新案件',
  },
  home: {
    tagline:
      '看似平凡的羽球聚會，背後藏著最佳配對的謎題。名偵探將推理出實力最均衡的組合、記錄每一條線索——真相只有一個！',
    start: '開始推理！🔍',
  },
  steps: { back: '回到上一條線索' },
  courts: {
    title: '線索 1：案發現場有幾處？',
    subtitle: '請確認今天可使用的羽球場（現場）數量',
    back: '回到事務所',
    next: '下一條線索（選擇推理方向）',
  },
  mode: {
    title: '線索 2：選擇推理方向',
    subtitle: '決定偵探用什麼邏輯為大家分組',
    similarTitle: 'A. 實力相近推理',
    similarDescription: '積分相近的嫌疑人互相對決，誰也瞞不過誰。',
    balancedTitle: 'B. 強弱互補推理',
    balancedDescription: '高手搭配新手，讓兩隊總積分剛好相當——這就是唯一的解答。',
    mixedTitle: 'C. 綜合推理',
    mixedDescription: '兩種推理交替運用，依場次數自動調整比例。',
    next: '下一條線索（選擇搭檔）',
  },
  strategy: {
    title: '線索 3：選擇辦案搭檔',
    subtitle: '決定誰來協助你安排比賽',
    assistTitle: '少年偵探團 (Assist)',
    assistSubtitle: '隨時支援，即時補位',
    assistDescription:
      '偵探團隨時盯著候場名單，當對戰組合不足時，立刻「補上一場」建議對戰。適合喜歡親自分組、只在空檔需要支援的偵探。缺點是若很少親自安排，常常會是同一群人輪流上場。',
    autoTitle: '名偵探全權推理 (Auto)',
    autoSubtitle: '一次看穿全局',
    autoDescription:
      '名偵探以「一輪 (Session)」為單位，一次推理出所有候場者的對戰組合，讓分組最多樣、輪替最公平。適合全權交給名偵探，盡量別干擾推理，比賽最順暢。',
    next: '下一條線索（列出嫌疑人）',
  },
  players: {
    title: '線索 4：嫌疑人名單',
    subtitle: '列出所有到場的人物（至少 4 位）',
    add: '列入名單',
    total: '嫌疑人總數',
    active: '在場',
    resting: '有不在場證明',
    generateTest: '產生測試嫌疑人',
    bulkImport: '整批調閱資料',
    empty: '尚無嫌疑人——這案子太乾淨了',
    statusActive: '在場',
    statusResting: '有不在場證明',
    next: '開始辦案（開始打球）',
    nextWhileEditing: '名單確認（回到事務所）',
  },
  lobby: {
    title: '🔍 偵探事務所',
    assistBadge: '偵探團支援',
    autoBadge: '全權推理',
    courts: '現場',
    playing: '調查中',
    waiting: '候場',
    total: '嫌疑人',
    editRoster: '修改名單',
    manualMatch: '指名對決',
    finish: '真相大白',
    manualQueue: '指名的對決 (優先上場)',
    suggested: '推理出的最佳對決',
    autoHint: '(全權推理：已預先推理)',
    notEnoughPlayers: '候場人數不足 4 位，線索不夠，無法推理。',
    computing: '正在推理最佳組合……',
    reshuffle: '重新推理',
    allBusyTitle: '每一組都有人還在現場',
    allBusyHint: '可以等場上比賽結束，或讓偵探重新推理分組，立即開始。',
    autoAdjust: '重新推理分組',
  },
  court: {
    name: (courtId: number) => `第 ${courtId} 號現場`,
    win: '破案！',
    draw: '懸案',
    requeue: '重新調查',
    noScore: '證據不足',
    idle: '現場封鎖中……',
  },
  match: { goToCourt: '前往現場', goNow: '立即前往', recommended: '推理結果' },
  waiting: { title: '候場人物', empty: '所有人都已到現場或排定', neverPlayed: '尚未出場' },
  planned: { title: '出場順序', hint: '（現場一空出就依序前往）' },
  dialogs: {
    finishTitle: '要揭曉真相了嗎？',
    finishBody: em('偵探將', '停止推理新的對決', '，並公布最終戰績。'),
    finishUnfinished: wrap('目前還有 ', ' 起案件尚未偵破，不會列入最終戰績。'),
    finishConfirm: '揭曉真相',
    finishCancel: '繼續調查',
    noScoreTitle: '以證據不足結案嗎？',
    noScoreBody: em('只會記錄一次', '「出場次數」', '，積分、勝負與得分都不改變。'),
    noScoreCourtCleared: '現場將解除封鎖。',
    noScoreConfirm: '證據不足結案',
    resultTitle: '真相只有一個！',
    resultSubtitle: '積分已更新',
    resultConfirm: '結案',
    historyTitle: '案件卷宗',
    statsTitle: '嫌疑人狀態一覽',
  },
  stats: {
    title: '📁 結案報告：最終戰績',
    subtitle: '線索 5：比賽統計',
    copy: '抄錄嫌疑人名單',
    history: '辦案經過',
    done: '全案終結（清空回到事務所）',
  },
  announcement: {
    intro: '真相只有一個！嫌疑人',
    versus: '與',
    outro: atCourt((courtId) => `請立刻前往第 ${courtId} 號現場`, '請立刻前往現場'),
  },
};

/** Mahjong-parlour tone: courts are tables, players are 雀友, winning is 胡了, a draw is 流局. */
const MAHJONG_COPY: CopyOverrides = {
  app: {
    restoreTitle: '上一將還沒打完！',
    restoreDescription: '牌桌上還留著上次沒打完的牌局，要接著摸下去嗎？',
    restoreConfirm: '接著摸',
    restoreCancel: '洗牌重來',
  },
  home: {
    tagline: '雀神坐鎮！自動配出旗鼓相當的牌搭子、記好每一把的輸贏，讓每一次揮拍都像自摸一樣爽快！',
    start: '開局！擲骰子 🎲',
  },
  steps: { back: '倒回上一手' },
  courts: {
    title: '第一圈：開幾張牌桌？',
    subtitle: '選一下今天有幾面羽球場（牌桌）',
    back: '離開雀館',
    next: '下一步（選擇打法）',
  },
  mode: {
    title: '第二圈：選擇打法',
    subtitle: '決定雀神怎麼幫大家配牌搭子',
    similarTitle: 'A. 旗鼓相當打法',
    similarDescription: '牌技相近的湊一桌，每一把都是硬仗。',
    balancedTitle: 'B. 老手帶新手',
    balancedDescription: '雀神搭配菜鳥，兩隊總分剛剛好，誰也不吃虧。',
    mixedTitle: 'C. 混一色打法',
    mixedDescription: '兩種打法輪流來，依局數自動調配比例。',
    next: '下一步（找幫手）',
  },
  strategy: {
    title: '第三圈：誰來幫你配牌',
    subtitle: '決定由誰協助安排牌局',
    assistTitle: '看牌軍師 (Assist)',
    assistSubtitle: '缺人就補，隨時上桌',
    assistDescription:
      '軍師盯著候桌的人，牌搭子不夠時就立刻「補一桌」建議對戰。適合喜歡自己配桌、只在空檔需要幫忙的雀友。缺點是若很少自己安排，常常會是同一群老搭子輪來輪去。',
    autoTitle: '雀神坐鎮 (Auto)',
    autoSubtitle: '一次洗好牌，公平輪桌',
    autoDescription:
      '雀神以「一圈 (Session)」為單位，一次替所有候桌的人配好牌局，讓搭配最多樣、輪替最公平。適合全權交給雀神，盡量別插手，牌局最順。',
    next: '下一步（找牌搭子）',
  },
  players: {
    title: '第四圈：牌搭子名單',
    subtitle: '登記今天來打牌（球）的人（至少 4 位，才湊得成一桌）',
    add: '入座',
    total: '雀友總數',
    active: '上桌',
    resting: '觀戰',
    generateTest: '找幾個測試牌搭子',
    bulkImport: '整團報到',
    empty: '一個人都沒有，連三缺一都湊不到！快找人！',
    statusActive: '準備上桌',
    statusResting: '在旁邊觀戰',
    next: '開局！（開始打球）',
    nextWhileEditing: '名單好了（回雀館）',
  },
  lobby: {
    title: '🀄 雀神大廳',
    assistBadge: '軍師補位',
    autoBadge: '雀神坐鎮',
    courts: '牌桌',
    playing: '開打中',
    waiting: '候桌',
    total: '雀友',
    editRoster: '修改名單',
    manualMatch: '自己湊桌',
    finish: '結算籌碼',
    manualQueue: '自己湊的桌 (優先上桌)',
    suggested: '雀神配好的牌局',
    autoHint: '(雀神坐鎮：牌已洗好)',
    notEnoughPlayers: '候桌的人不到 4 位——三缺一，湊不成一桌！',
    computing: '雀神正在洗牌理牌……🀄',
    reshuffle: '重新洗牌',
    allBusyTitle: '每一桌都有人還在打',
    allBusyHint: '可以等這一把打完，或請雀神重新配牌，立刻開局。',
    autoAdjust: '請雀神換牌',
  },
  court: {
    name: (courtId: number) => `${courtId} 號牌桌`,
    win: '胡了！',
    draw: '流局',
    requeue: '退回重配',
    noScore: '不算台',
    idle: '牌桌空著，等人上桌……',
  },
  match: { goToCourt: '上桌', goNow: '立刻上桌', recommended: '雀神推薦' },
  waiting: { title: '候桌雀友', empty: '所有人都已上桌或排好了', neverPlayed: '還沒上桌' },
  planned: { title: '上桌順序', hint: '（牌桌一空出就依序上桌）' },
  dialogs: {
    finishTitle: '要結算籌碼了嗎？',
    finishBody: em('雀神將', '不再開新的牌局', '，並結算最終戰績。'),
    finishUnfinished: wrap('還有 ', ' 桌還沒打完，這些不列入最終結算。'),
    finishConfirm: '結算籌碼',
    finishCancel: '再打一圈',
    noScoreTitle: '這一把不算台嗎？',
    noScoreBody: em('只會增加大家的', '「上桌次數」', '，積分、勝負和得分都不變。'),
    noScoreCourtCleared: '這張牌桌會空出來。',
    noScoreConfirm: '不算台',
    resultTitle: '胡牌！這一把結束',
    resultSubtitle: '積分（籌碼）已更新',
    resultConfirm: '收錢！',
    historyTitle: '牌譜紀錄',
    statsTitle: '雀友狀態一覽',
  },
  stats: {
    title: '🀄 最終結算：戰績排行',
    subtitle: '散場：牌局統計',
    copy: '抄下雀友名單',
    history: '牌譜',
    done: '散場回家（清空回到首頁）',
  },
  announcement: {
    intro: '雀神點名',
    versus: '對上',
    outro: atCourt((courtId) => `請到 ${courtId} 號牌桌，開局`, '請上桌開局'),
  },
};

const OVERRIDES: Record<ThemeId, CopyOverrides> = {
  default: {},
  fairy: FAIRY_COPY,
  insurance: INSURANCE_COPY,
  tech: TECH_COPY,
  lawsuit: LAWSUIT_COPY,
  greek: GREEK_COPY,
  slacker: SLACKER_COPY,
  foodie: FOODIE_COPY,
  travel: TRAVEL_COPY,
  detective: DETECTIVE_COPY,
  mahjong: MAHJONG_COPY,
};

const mergeCopy = (overrides: CopyOverrides): Copy =>
  Object.fromEntries(
    (Object.keys(CLASSIC_COPY) as (keyof Copy)[]).map((section) => [
      section,
      { ...CLASSIC_COPY[section], ...overrides[section] },
    ]),
  ) as Copy;

// Built once so every `getCopy` call for a theme returns the same object.
const COPY_BY_THEME = Object.fromEntries(
  THEME_IDS.map((id) => [id, mergeCopy(OVERRIDES[id])]),
) as Record<ThemeId, Copy>;

export const getCopy = (id: ThemeId = DEFAULT_THEME_ID): Copy => COPY_BY_THEME[id];
